!==PROGRAM TO FIND THE SUMMATION OF A SERIES
     PROGRAM SUMMATION
     SUM=0.0
     DO 15 I=1,100
     DO J=1,I
       SUM=SUM+1.0/REAL(J)
       ENDDO
 15  CONTINUE
     WRITE(6,20) SUM
 20  FORMAT(3X,"SUM=",F12.5)
     STOP
     END