!==PROGRAM TO FIND THE SUM OF A SERIES
     PROGRAM SUMMATION
     INTEGER FACT
     E(X)=1+X+X**2/FACT(2)+X**3/FACT(3)+X**4/FACT(4)
     PRINT*,"E^5=",E(5.0)
     PRINT*,"E^1.5=",E(1.5)
     END PROGRAM
!==FUNCTION SUBPRGRAM
     FUNCTION FACT(N)
     INTEGER FACT
     FACT=1
     DO I=1,N
       FACT=FACT*I
     ENDDO
     RETURN
     END