PROGRAM GCD
    INTEGER A,B,REMAINDER,QUOTIENT
	PRINT*,"ENTER TWO NUMBERS(INTEGER):"
    READ*,A,B
    PRINT*,"RUNNING CALCULATIONS"
    IF(A.LT.B) THEN
      MIN = A
      MAX = B
    ELSE
      MIN = B
      MAX = A
    ENDIF
    PRINT*,"SMALL NUMBER IS ",MIN," AND LARGE NUMBER IS ",MAX
    PRINT*,"PERFORMING ALGORITHM"
    REMAINDER = MOD(MAX,MIN)
    QUOTIENT = MAX/MIN
10  FORMAT(3X,I7,1X,"=",1X,I4,1X,"*",1X,I7,1X,"+",1X,I7)
    WRITE(6,10)  MAX,QUOTIENT,MIN,REMAINDER
    DO WHILE(REMAINDER.NE.0) 
      MAX = MIN
      MIN = REMAINDER
      QUOTIENT = MAX/MIN
      REMAINDER = MOD(MAX,MIN)
      WRITE(6,10)  MAX,QUOTIENT,MIN,REMAINDER
    ENDDO
    PRINT*,"GCD IS: ",MIN
    ENDPROGRAM